[#168] Some FAQs about nacos2.0 port exposure should be added into na…
nacos-group/nacos-group.github.io pull request #169
Opened 2021-03-30 02:49 UTC by JackSun-Developer

…cos document.

## What is the purpose of the change

fix ISSUE #168 

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2021-03-30 03:03 UTC, KomachiSion requested changes

2021-03-30 03:03 UTC, KomachiSion commented on docs/zh-cn/2.0.0-compatibility.md
> +os2.0.0 的启动
What's this?

2021-03-31 01:37 UTC, KomachiSion requested changes

2021-04-06 11:43 UTC, JackSun-Developer commented
I have changed it

2021-04-23 06:17 UTC, merged