添加 nacos 底层原理的文章（请求如何注册的、distro 协议）
nacos-group/nacos-group.github.io pull request #280
Opened 2022-05-13 13:21 UTC by Jackson0714

## What is the purpose of the change

添加 nacos 底层原理的文章（请求如何注册的、distro 协议）

2022-05-14 23:47 UTC, Jackson0714 commented
图片的路径是否需要替换？如何上传到官网的图床？

2022-05-20 05:52 UTC, KomachiSion requested changes

2022-05-20 05:52 UTC, KomachiSion commented on docs/zh-cn/nacos-reigster-mechanism.md
> +上篇我们讲到加上一个注解 `@EnableDiscoveryClient` 就可以使服务自动注册到 Nacos。
Where is the `上篇`?

2022-05-20 05:53 UTC, KomachiSion commented
> 图片的路径是否需要替换？如何上传到官网的图床？

最好是能够替换，可以参考下其他blog， 放在本项目的img目录下即可。

2022-05-30 12:27 UTC, Jackson0714 commented on docs/zh-cn/nacos-reigster-mechanism.md
> +上篇我们讲到加上一个注解 `@EnableDiscoveryClient` 就可以使服务自动注册到 Nacos。
这句话已经去掉了。上篇其实是我之前写的另外一篇：如何使用 Nacos 的，没有放进来。

2022-05-30 12:29 UTC, Jackson0714 commented
> 图片的路径是否需要替换？如何上传到官网的图床？

> 最好是能够替换，可以参考下其他blog， 放在本项目的img目录下即可。

@KomachiSion  已经放到本项目的 img 文件夹下了，单独创建了两个目录 `nacos-distro-mechanism`、`nacos-reigster-mechanism`。

2022-05-31 01:44 UTC, KomachiSion approved these changes

2022-05-31 01:46 UTC, KomachiSion commented
@Jackson0714 辛苦在PR中回复一下作者信息，姓名（或者公众号昵称）和联系邮箱。

另外文章中是否需要添加类似内容：

`转载且编辑自xxxx`？

2022-05-31 04:15 UTC, Jackson0714 commented
> 辛苦在PR中回复一下作者信息，姓名（或者公众号昵称）和联系邮箱。

公众号昵称：悟空聊架构
联系邮箱：jackson0585@163.com

2022-05-31 04:23 UTC, Jackson0714 commented
> `转载且编辑自xxxx`？

@KomachiSion 已在文首添加该段内容，帮忙看下是否可行。

2022-05-31 06:14 UTC, merged