add docs for address plugin
nacos-group/nacos-group.github.io pull request #310
Opened 2022-09-29 08:09 UTC by MRGUOKING

## What is the purpose of the change

add docs for address plugin

## Brief changelog

add docs for address plugin

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2022-10-09 10:31 UTC, chuntaojun requested changes

2022-10-09 10:31 UTC, chuntaojun commented on docs/zh-cn/address-plugin.md
> +开发Nacos服务端鉴权插件，首先需要依赖鉴权插件的相关API
开发Nacos服务端寻址插件

2022-10-09 10:31 UTC, chuntaojun commented on docs/zh-cn/address-plugin.md
> +nacos.core.member.lookup.type=${authServiceName}
addressPluginName

2022-10-20 10:05 UTC, brotherlu-xcq approved these changes

2022-10-24 08:26 UTC, brotherlu-xcq approved these changes
LGTM

2022-10-24 08:35 UTC, KomachiSion approved these changes

2022-10-24 08:35 UTC, merged