add custom-environment-plugin.md
nacos-group/nacos-group.github.io pull request #324
Opened 2022-11-05 08:40 UTC by godhth

## What is the purpose of the change

XXXXX

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2022-12-01 01:56 UTC, KomachiSion requested changes

2022-12-01 01:56 UTC, KomachiSion commented on docs/en-us/v2/plugin/custom-environment-plugin.md
> +# 自定义环境变量插件
Not translated

2022-12-02 07:39 UTC, godhth commented on docs/en-us/v2/plugin/custom-environment-plugin.md
> +# 自定义环境变量插件
done

2022-12-07 03:46 UTC, KomachiSion approved these changes

2022-12-07 03:46 UTC, merged