添加导入sql文件的步骤
nacos-group/nacos-group.github.io pull request #364
Opened 2023-03-21 12:15 UTC by 985492783

## What is the purpose of the change

XXXXX

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2023-03-21 12:18 UTC, 985492783 commented
linked https://github.com/alibaba/nacos/issues/9983

2023-03-31 06:36 UTC, KomachiSion requested changes

2023-03-31 06:36 UTC, KomachiSion commented on docs/zh-cn/v2/quickstart/quick-start.md
> +## 3.导入sql文件
快速开始应该是单例模式启动，不需要初始化sql吧。

2023-04-10 11:47 UTC, KomachiSion commented
修改内容错误，快速开始是以单例模式启动，提供给首次接触或刚接触不久的同学进行部署的。

针对mysql部署的情况，如何导入sql，如何配置，需要新增其他的进阶文档来引导。

2023-04-10 11:47 UTC, closed without merging