doc:dev-issue-757
nacos-group/nacos-group.github.io pull request #758
Opened 2024-08-06 12:20 UTC by Tinywan

dev-issue-757

2024-08-06 12:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nacos-group/nacos-group.github.io?pullRequest=758) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-group.github.io?pullRequest=758) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-group.github.io?pullRequest=758) it.</sub>

2024-08-06 12:27 UTC, KomachiSion requested changes
另外CLA麻烦签署一下。

2024-08-06 12:27 UTC, KomachiSion commented on docs/zh-cn/v2/guide/user/other-language.md
> +* [PHP](https://github.com/workbunny/webman-nacos)
建议添加一下说明：该sdk由社区自行维护。

因为这个sdk没有贡献到nacos-group里。

或者你看下是否愿意贡献到nacos-group中？如果贡献并持续保持维护的话，可以提名committer的。

2024-08-06 12:27 UTC, KomachiSion commented
> [![CLA assistant check](https://camo.githubusercontent.com/fbf2b4a56b8f8dacb3fb4f7f3cf7877b8c27f9cfee8546ff24c8df94facca0f6/68747470733a2f2f636c612d617373697374616e742e696f2f70756c6c2f62616467652f6e6f745f7369676e6564)](https://cla-assistant.io/nacos-group/nacos-group.github.io?pullRequest=758) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-group.github.io?pullRequest=758) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-group.github.io?pullRequest=758) it.

CLA需要签署一下

2024-08-06 12:28 UTC, KomachiSion commented
还有， 同学你的分支是从什么分支checkout出来的， 就修改一行为什么还有冲突需要解决啊。。

2024-08-06 12:33 UTC, Tinywan commented on docs/zh-cn/v2/guide/user/other-language.md
> +* [PHP](https://github.com/workbunny/webman-nacos)
这个要怎么贡献到nacos-group

2024-08-06 12:34 UTC, Tinywan commented
> 还有， 同学你的分支是从什么分支checkout出来的， 就修改一行为什么还有冲突需要解决啊。。

master 分支，我看只有一行 怎么会冲突呢

![image](https://github.com/user-attachments/assets/dbe63267-5233-41a6-865d-044c1b13c164)

2024-08-06 12:39 UTC, Tinywan commented
> 还有， 同学你的分支是从什么分支checkout出来的， 就修改一行为什么还有冲突需要解决啊。。

已签署

2024-08-07 02:13 UTC, KomachiSion commented on docs/zh-cn/v2/guide/user/other-language.md
> +* [PHP](https://github.com/workbunny/webman-nacos)
是个人项目还是公司项目？ 也就是项目的版权归属是？

2024-08-07 05:35 UTC, KomachiSion commented
[develop-astro-nacos](https://github.com/nacos-group/nacos-group.github.io/tree/develop-astro-nacos) 请用这个分支作为基础分支

2024-08-07 06:49 UTC, Tinywan commented on docs/zh-cn/v2/guide/user/other-language.md
> +* [PHP](https://github.com/workbunny/webman-nacos)
个人项目，可以贡献到nacos-group中不？

2024-08-07 06:53 UTC, Tinywan commented
> [develop-astro-nacos](https://github.com/nacos-group/nacos-group.github.io/tree/develop-astro-nacos) 请用这个分支作为基础分支

https://github.com/nacos-group/nacos-group.github.io/pull/760

2024-08-07 09:15 UTC, closed without merging