UPDATE parameters-check.md 实例元数据注释
nacos-group/nacos-group.github.io pull request #763
Opened 2024-08-09 16:14 UTC by fuhouyu

## What is the purpose of the change

resolves alibaba/nacos#12466
对该issue在parameters-check.md 添加注释。 

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `npm run build`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2024-08-09 16:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nacos-group/nacos-group.github.io?pullRequest=763) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nacos-group/nacos-group.github.io?pullRequest=763) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nacos-group/nacos-group.github.io?pullRequest=763) it.</sub>

2024-08-12 02:00 UTC, KomachiSion requested changes

2024-08-12 02:00 UTC, KomachiSion commented on src/content/docs/next/zh-cn/manual/user/parameters-check.md
> +|命名空间ID|64|只允许字母数字下划线以及"-"字符，对应正则表达式：`^[\w-]+`｜|
这行是多了个｜吗？

2024-08-12 02:42 UTC, fuhouyu commented on src/content/docs/next/zh-cn/manual/user/parameters-check.md
> +|命名空间ID|64|只允许字母数字下划线以及"-"字符，对应正则表达式：`^[\w-]+`｜|
确实是的。老师，我改下。……

2024-08-13 01:39 UTC, KomachiSion approved these changes

2024-08-13 06:26 UTC, merged